---
# Wymagane kolekcje Ansible
# Plik: requirements.yml

collections:
  # Community General - podstawowe moduły
  - name: community.general
    version: ">=7.0.0"
    
  # POSIX - moduły dla systemów Unix/Linux
  - name: ansible.posix
    version: ">=1.4.0"
    
  # Community Crypto - zarządzanie certyfikatami SSL/TLS
  - name: community.crypto
    version: ">=2.0.0"
    
  # Community MySQL - zarządzanie bazami MySQL/MariaDB
  - name: community.mysql
    version: ">=3.0.0"
    
  # Community PostgreSQL - zarządzanie bazami PostgreSQL
  - name: community.postgresql
    version: ">=2.0.0"
    
  # Community Docker - zarządzanie kontenerami Docker
  - name: community.docker
    version: ">=3.0.0"
    
  # Community Grafana - konfiguracja Grafana
  - name: community.grafana
    version: ">=1.0.0"

# Wymagane role (opcjonalnie)
roles:
  # Przykładowe role z Ansible Galaxy
  # - name: geerlingguy.security
  #   version: "1.7.1"
  # - name: geerlingguy.firewall  
  #   version: "2.5.0"